server:
  port: 8000

spring:
  application:
    name: cloud-order-service
  profiles:
    active: dev
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    openfeign:
      client:
        config:
          default:
            connect-timeout: 3000
            read-timeout: 3000
          cloud-payment-service:
            connect-timeout: 20000
            read-timeout: 20000
      httpclient:
        hc5:
          enabled: true
      compression:
        request:
          enabled: true
          min-request-size: 2048
        response:
          enabled: true
      circuitbreaker:
        enabled: true
        group:
          enabled: true
#    loadbalancer:
#      retry:
#        enabled: true
#        max-retries-on-same-service-instance: 2
logging:
  level:
    com:
      cl:
        common:
          api:
            PayApi: debug
#        max-retries-on-next-service-instance: 1

#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        slidingWindowType: COUNT_BASED
#        slidingWindowSize: 6
#        minimumNumberOfCalls: 3
#        wait-duration-in-open-state: 5s
#        permittedNumberOfCallsInHalfOpenState: 2
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        failureRateThreshold: 50
#        recordExceptions:
#          - org.springframework.web.client.HttpServerErrorException
#          - java.lang.NullPointerException
#          - java.util.concurrent.TimeoutException
#          - org.springframework.web.client.ResourceAccessException


#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        slidingWindowType: TIME_BASED
#        slidingWindowSize: 6
#        minimumNumberOfCalls: 3
#        wait-duration-in-open-state: 5s
#        permittedNumberOfCallsInHalfOpenState: 2
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        failureRateThreshold: 50
#        recordExceptions:
#          - org.springframework.web.client.HttpServerErrorException
#          - java.lang.NullPointerException
#          - java.util.concurrent.TimeoutException
#          - org.springframework.web.client.ResourceAccessException
#    instances:
#      cloud-payment-service:
#        baseConfig: default


resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        slidingWindowType: COUNT_BASED
#        slidingWindowSize: 6
#        minimumNumberOfCalls: 2
#        slow-call-duration-threshold: 500ms
#        slow-call-rate-threshold: 50     # 50%
#        wait-duration-in-open-state: 5s
#        permittedNumberOfCallsInHalfOpenState: 2
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        failureRateThreshold: 100
#        recordExceptions:
#          - org.springframework.web.client.HttpServerErrorException
#          - java.lang.NullPointerException
#          - java.util.concurrent.TimeoutException
#          - org.springframework.web.client.ResourceAccessException
  bulkhead:
    configs:
      default:
        max-concurrent-calls: 2
        max-wait-duration: 1s
    instances:
      cloud-payment-service:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeout-duration:
          20s

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,circuitbreakers
  health:
    circuitbreakers:
      enabled: true
    logging:
      level:
        org.springframework.aop: DEBUG
        org.springframework.context: DEBUG
        io.github.resilience4j: TRACE